[WIP] AUTH
RocketChat/EmbeddedChat pull request #12
Opened 2022-07-06 06:25 UTC by sidmohanty11

# Authentication

## Acceptance Criteria fulfillment

- [ ] Google SSO Auth with RC API

Fixes # (issue)

## Video/Screenshots

2022-07-12 14:59 UTC, sidmohanty11 commented
## v1

https://user-images.githubusercontent.com/73601258/178520888-b1ddb508-600d-49a2-9d31-8ae54e5c5a69.mp4

2022-07-17 04:13 UTC, RonLek commented
@sidmohanty11 have we shifted the "Sign in with Google" button within the message box (if the user isn't logged in) as we discussed? Also the emoji button within the message box shouldn't display if the user isn't signed in.

2022-07-17 04:18 UTC, RonLek requested changes

2022-07-17 04:18 UTC, RonLek commented on playground/.env[example]
> +REACT_APP_GOOGLE_CLIENT_ID=
Leave a new line.

2022-07-22 07:47 UTC, sidmohanty11 commented
removed commit (in full) - removed `/me` call and logout user if cookies invalid

when I used this commit message, it said /me isn't a directory and just kept removed as the commit message :(

2022-07-22 07:49 UTC, sidmohanty11 commented
Done @RonLek sir!

2022-07-23 06:36 UTC, sidmohanty11 commented
Done @RonLek sir!

2022-07-25 07:52 UTC, RonLek approved these changes
This was a big one! Great work @sidmohanty11 . LGTM.

2022-07-25 07:52 UTC, merged