fix:changed hardcoded url to RCInstance.getHost() (RocketChat#132)
RocketChat/EmbeddedChat pull request #133
Opened 2023-02-15 15:48 UTC by CulturalProfessor

## Fixed Task 4 of #132 

### I have changed hardcoded url localhost:3000 from to RCInstance.getHost() 

## Video/Screenshots
![Screenshot from 2023-02-15 21-15-01](https://user-images.githubusercontent.com/92238941/219078250-fc18daf0-ebaf-456d-a644-67326b173237.png)

2023-02-15 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/EmbeddedChat?pullRequest=133) it.</sub>

2023-02-15 18:20 UTC, sidmohanty11 requested changes
Thanks @CulturalProfessor for the PR!

2023-02-15 18:20 UTC, sidmohanty11 commented on src/components/Attachments/Attachment.js
>  const Attachment = ({ attachment, host }) => {
Let's use `host` from here directly

2023-02-15 18:37 UTC, CulturalProfessor commented on src/components/Attachments/Attachment.js
>  const Attachment = ({ attachment, host }) => {
Ok I will use **host** directly from here on.

2023-02-16 10:52 UTC, sidmohanty11 approved these changes

2023-02-16 10:53 UTC, merged