Fixed unused import: #132
RocketChat/EmbeddedChat pull request #149
Opened 2023-02-22 01:40 UTC by honey-grapes

Hi, I removed unused import mentioned in Task 8 of issue #132. The task is small so I don't believe a screenshot is required. Also, task #132 is closed but it has not been completed yet. It might have been closed mistakenly.

Thank you!

2023-02-22 01:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=149) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=149) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/EmbeddedChat?pullRequest=149) it.</sub>

2023-02-26 07:09 UTC, sidmohanty11 requested changes
@honey-grapes thanks for the PR! Can you please remove the console.log from that file too?

2023-03-03 16:41 UTC, honey-grapes commented
> @honey-grapes thanks for the PR! Can you please remove the console.log from that file too?

Hi Sid, I have removed it!

2023-03-04 14:57 UTC, sidmohanty11 approved these changes
Thanks @honey-grapes !

2023-03-04 14:58 UTC, merged