Fix/#238 replace message emoji
RocketChat/EmbeddedChat pull request #262
Opened 2023-10-09 15:58 UTC by umangutkarsh

# Brief Title: Replace MesasgeEmoji

## Acceptance Criteria fulfillment

- [X] Task 1: Replace MessageEmoji component with own component

Fixes #238

2023-10-09 15:58 UTC, umangutkarsh commented
Hey @abhinavkrin , please review the PR, and LMN if any changes are required or if there's any issue.
Thanks

2023-10-16 17:38 UTC, abhinavkrin reviewed
1. You should end the contents of a file with a new line. 
2. The MessageEmoji.js file is black.

2023-10-16 17:45 UTC, umangutkarsh commented on .editorconfig
> +indent_size = 2
Added new line in this file. Which other files should I edit?

2023-10-16 17:53 UTC, abhinavkrin commented on .editorconfig
> +indent_size = 2
I would suggest checking the changed files of this PR.
Also, could you check why MessageEmoji.js is an empty file.

2023-10-16 18:31 UTC, abhinavkrin requested changes
1. End files with a new line. Check PR file changes to see which files are not ended with a LN. (recommended)
2. Please use an eslint plugin to check the styling errors and fix them (recommended)
3. Changes break the size of the emoji in the message and reaction list. It appears to be larger than it should be. (MUST) 
![emoji-size-change](https://github.com/RocketChat/EmbeddedChat/assets/15830206/a26f100b-ee51-49ca-b1dc-60800aec03e1)

2023-10-17 11:36 UTC, umangutkarsh commented
> 1. End files with a new line. Check PR file changes to see which files are not ended with a LN. (recommended)
> 2. Please use an eslint plugin to check the styling errors and fix them (recommended)
> 3. Changes break the size of the emoji in the message and reaction list. It appears to be larger than it should be. (MUST) 
> ![emoji-size-change](https://github.com/RocketChat/EmbeddedChat/assets/15830206/a26f100b-ee51-49ca-b1dc-60800aec03e1)
> 

@abhinavkrin, will soon look into it.

2023-10-17 20:42 UTC, abhinavkrin commented on .gitignore
> +.vscode
end with new line

2023-10-17 20:42 UTC, abhinavkrin commented on yarn.lock
> +
end with new line

2023-10-17 20:44 UTC, abhinavkrin requested changes
Almost read to merge.
1. Please commit only those files which are related to your changes
2. End files with new lines https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-10-17 21:20 UTC, umangutkarsh commented
> Almost read to merge.
> 
> 1. Please commit only those files which are related to your changes
> 2. End files with new lines https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

@abhinavkrin, I had to commit files other than those related to changes since earlier I was getting this error -> `no babel config file detected`. To resolve this, had to add some changes to `.eslintrc.json` file. But then I reverted those back since adding some configuration in `settings.json` resolved this error. 
But since I use `Prettier-Code formatter`, these code formatting are automatically applied when I saved the above files.

2023-10-17 21:29 UTC, abhinavkrin reviewed
Hey! Why is `.yarn/releases/yarn-berry.cjs` included in the commit and is an empty file?

2023-10-18 07:15 UTC, umangutkarsh commented
> Hey! Why is `.yarn/releases/yarn-berry.cjs` included in the commit and is an empty file?

<img width="935" alt="berry" src="https://github.com/RocketChat/EmbeddedChat/assets/95426993/1d707fb7-232b-4d6d-b533-176a019caeec">
This is `yarn-berry.cjs` on my local machine^

2023-10-18 07:20 UTC, abhinavkrin approved these changes
LGTM!

2023-10-18 07:20 UTC, merged