Feat/#341 Delete Confirmation Modal
RocketChat/EmbeddedChat pull request #342
Opened 2023-12-04 06:32 UTC by umangutkarsh

# Brief Title
Confirm Modal implementation to delete message, just like for 'report-message' is implemented, so that the message is not deleted by mistake.

## Acceptance Criteria fulfillment

- [X] Implement delete message modal.
- [X] Use modal in `MessageToolbox.js`  

Fixes #341 

## Video/Screenshots
[delete.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/2017dd2c-082a-4199-b46a-5103b6750671)

2023-12-07 13:15 UTC, abhinavkrin requested changes

2023-12-07 13:15 UTC, abhinavkrin commented on packages/react/src/components/Message/MessageToolbox.js
> +import { useToastStore } from '../../store';
This was removed recently and we are no longer using the store for toasts. I think this is the older code.

2023-12-07 13:15 UTC, abhinavkrin commented on packages/react/src/components/Message/MessageToolbox.js
> +  const [deleteId, setDeleteId] = useState('');
deleteId is state is never used.

2023-12-07 18:42 UTC, umangutkarsh commented
Hey. Thanks for reviewing. Will address the changes asap. 
Thanks.

2023-12-08 06:28 UTC, umangutkarsh commented on packages/react/src/components/Message/MessageToolbox.js
> +  const handleDeleteMessage = async (message) => {
Moved the `handleDeleteMessage()` to it's old location and used it as a prop.

2023-12-08 06:30 UTC, umangutkarsh commented
Hi @abhinavkrin . I've made the changes, there were some conflicts with the develop branch that's why the `toastStore`  was being used. Please review the PR and if anything further is required, please let me know.
Thanks.

2023-12-13 10:30 UTC, abhinavkrin approved these changes
Thanks @umangutkarsh. This will prevent users from accidentally deleting a message. I have added a minor change in which the message preview is shown in the modal.
![delete_modal](https://github.com/RocketChat/EmbeddedChat/assets/15830206/8532cd2b-91cb-427b-b818-2a3c43c10cfb)

2023-12-13 10:32 UTC, merged