username's handled as per RC core repo
RocketChat/EmbeddedChat pull request #60
Opened 2022-11-20 20:46 UTC by ayush3160

# Username's are handled as per the RC core repo

## Acceptance Criteria fulfillment

- [x] Checking If the username already exists or not.
- [x] Support for foreign language name's

Fixes #50 

## Video/Screenshots

2022-11-20 20:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=60) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=60) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/EmbeddedChat?pullRequest=60) it.</sub>

2022-12-03 12:18 UTC, ayush3160 commented
Hi @sidmohanty11 , can you please review the PR.

2022-12-03 12:21 UTC, sidmohanty11 commented
@ayush3160 I think you've missed my comment on this PR. Please take a look into it

2022-12-03 13:38 UTC, ayush3160 commented
@sidmohanty11 , I am not able to see any comments from your side.

2022-12-03 15:41 UTC, sidmohanty11 requested changes
Please convert it to a separate function

2022-12-04 07:01 UTC, ayush3160 commented on src/lib/api.js
> +      const res = await fetch(
@sidmohanty11 , I have separated username suggestion to a different function. Please have a look.

2022-12-05 11:01 UTC, sidmohanty11 requested changes
@ayush3160 please take a look.

Also, my suggestion will be to use VSCode's ESlint plugin. Didn't it run husky pre-commit hook when you committed?

2022-12-05 14:06 UTC, ayush3160 commented on src/lib/api.js
>    async updateUserUsername(userid, username) {
I have fixed this

2022-12-05 14:14 UTC, ayush3160 commented on src/lib/api.js
> +      const username = await this.getUserNameSuggestion();
@sidmohanty11 , Are you suggesting that we should first try to set username with the standard username firstname.lastname and if we get an error from this, Then we should make the username suggestion call and set the username. Let me know If I am getting this right.

2022-12-05 14:18 UTC, sidmohanty11 commented on src/lib/api.js
> +      const username = await this.getUserNameSuggestion();
@ayush3160 yup

2022-12-05 14:20 UTC, ayush3160 commented on src/lib/api.js
> +      const username = await this.getUserNameSuggestion();
Okay, I'll implement that.

2022-12-10 20:53 UTC, ayush3160 commented on src/lib/api.js
> +      const username = await this.getUserNameSuggestion();
@sidmohanty11 , I have changed the approach please have a look.

2022-12-12 05:08 UTC, sidmohanty11 commented on src/lib/api.js
> +      const username = await this.getUserNameSuggestion();
Amazing work!

2022-12-12 13:03 UTC, sidmohanty11 approved these changes
LGTM!

2022-12-12 13:03 UTC, merged