fix: Made UserClickable opening userInfo
RocketChat/EmbeddedChat pull request #700
Opened 2024-12-19 08:35 UTC by thepiyush-303

# Brief Title

## Acceptance Criteria fulfillment

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Fixes # (issue)
#699 

[Screencast from 2024-12-19 14-04-17.webm](https://github.com/user-attachments/assets/1846e01a-51a3-4f16-96d1-7189934857b7)

## Video/Screenshots

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

2024-12-19 08:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/EmbeddedChat?pullRequest=700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/EmbeddedChat?pullRequest=700) it.</sub>

2024-12-22 08:43 UTC, Spiral-Memory commented on packages/react/src/views/Message/MessageHeader.js
> +  const handleAvatarClick = () => {
Can you please change the function name ? It should be handleUsernameClick or something like that

2024-12-22 09:06 UTC, thepiyush-303 commented
Done.

2024-12-22 09:12 UTC, Spiral-Memory approved these changes

2024-12-22 09:26 UTC, Spiral-Memory approved these changes

2024-12-22 09:30 UTC, Spiral-Memory approved these changes

2024-12-22 10:04 UTC, Spiral-Memory approved these changes

2024-12-22 10:14 UTC, Spiral-Memory commented
Hi @thepiyush-303 
It is taking time to open sidebar, instead, open the user panel and inside that, show a throbber and load member details along with appropriate error if it fails

2024-12-22 10:16 UTC, Spiral-Memory requested changes
Hi @thepiyush-303
It is taking time to open sidebar, instead, open the user panel and inside that, show a throbber and load member details along with appropriate error if it fails

Take inspiration from how on userclick or avatar click, it shows userinfo

2024-12-23 08:27 UTC, thepiyush-303 commented
> Hi @thepiyush-303 It is taking time to open sidebar, instead, open the user panel and inside that, show a throbber and load member details along with appropriate error if it fails
> 
> Take inspiration from how on userclick or avatar click, it shows userinfo

Done.
Please check if anything I am missing.

2024-12-23 08:32 UTC, Spiral-Memory approved these changes

2024-12-23 18:52 UTC, Spiral-Memory approved these changes

2024-12-24 10:01 UTC, Spiral-Memory commented
Hey @thepiyush-303 
I don't think you've implemented the feedback.

2024-12-24 10:04 UTC, Spiral-Memory commented
Let me repeat my feedback.. 

On userclick (except here and all), open the sidebar first, show throbber, go ahead and make a request.. if success display user detail, otherwise display failed to fetch user info with the same design we have implemented in other sidepanels

2024-12-24 11:16 UTC, thepiyush-303 commented
Are you talking about `@mentions` click then open sidebar?

2024-12-24 11:18 UTC, Spiral-Memory commented
I think you're making user detail request, before opening the sidepanel.. first open it.. then make a request.. 

It is taking time to open sidepanel after click.. n if request is failing, the sidepanel isn't opening

2024-12-24 11:31 UTC, thepiyush-303 commented
I got you I will fix it.

2024-12-25 10:21 UTC, thepiyush-303 commented
@Spiral-Memory 
can you please show me a video?
I Think the process is working as what you said for.

2024-12-26 13:32 UTC, thepiyush-303 commented
@Spiral-Memory 
I tried finding the issue about userInfo is fetched before component renders but I could not find it happening I think it is working fine as your feedback. 
If I am missing something then please tell me.
[Screencast from 2024-12-26 18-49-10.webm](https://github.com/user-attachments/assets/01a467ae-a636-4604-863d-96c6c68425d3)

2025-01-01 12:44 UTC, Spiral-Memory approved these changes

2025-01-01 13:00 UTC, Spiral-Memory commented
Hi @thepiyush-303 

I am facing two issues with this implementation. Could you please help address them?  

1. Once a user is opened, clicking on another user does not open their details.  
2. When an error needs to be displayed, please ensure the UI remains consistent. For example, display the error in the center with an icon or proper formatting, instead of showing a raw error message to the user.  

I am attaching a video and a photo for your reference.  


https://github.com/user-attachments/assets/d39fef15-0284-4aaa-b556-dd9da46fdcd0

![image](https://github.com/user-attachments/assets/188be071-9622-47f7-bb0f-86868f117582)

2025-01-01 19:55 UTC, thepiyush-303 commented
![Screenshot from 2025-01-02 01-25-02](https://github.com/user-attachments/assets/0912d111-697a-46b5-a251-03cbea4b1fd7)
I fix the error page now it looks like this.

2025-01-01 21:11 UTC, thepiyush-303 commented
> I am facing two issues with this implementation. Could you please help address them?

   > Once a user is opened, clicking on another user does not open their details.
    When an error needs to be displayed, please ensure the UI remains consistent. For example, display the error in the center with an icon or proper formatting, instead of showing a raw error message to the user.

@Spiral-Memory  Both issues are fixed.
Thanks for you response.

[Screencast from 2025-01-02 02-38-18.webm](https://github.com/user-attachments/assets/194314ed-010a-48af-a756-dc040a136a7e)

2025-01-05 10:42 UTC, Spiral-Memory commented
> ![Screenshot from 2025-01-02 01-25-02](https://private-user-images.githubusercontent.com/157290995/399584901-0912d111-697a-46b5-a251-03cbea4b1fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNzM5ODgsIm5iZiI6MTczNjA3MzY4OCwicGF0aCI6Ii8xNTcyOTA5OTUvMzk5NTg0OTAxLTA5MTJkMTExLTY5N2EtNDZiNS1hMjUxLTAzY2JlYTRiMWZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQxMDQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmJhOWFiZjIwZTFmYzg4MGZhMGIwZjQ0ZDBhYjU5NTViMDUwNWQyZTRmZThhMDUyODZhNzgwY2M2OWVkZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lOfxDt8iLD_tjhTxJ_2AZHLwjyLJYGeahiQQ6oB-K-k) I fix the error page now it looks like this.

No need to display the exact error..

2025-01-05 11:32 UTC, thepiyush-303 commented
Removed showing actual error.

2025-01-05 13:10 UTC, thepiyush-303 commented
@Spiral-Memory 
any other changes?

2025-01-05 13:13 UTC, Spiral-Memory approved these changes

2025-01-26 11:53 UTC, thepiyush-303 commented
@Spiral-Memory 
can you please review the changes?

2025-02-07 17:46 UTC, thepiyush-303 commented
I did some unwanted changes and want to get rid of them but i lost this branch due to fresh clone closing it and will raise a new PR for it or add in one of my existing PRs.

2025-02-07 17:46 UTC, closed without merging