Edit Message Functionality Added
RocketChat/EmbeddedChat pull request #75
Opened 2023-01-04 13:24 UTC by ayush3160

# Implemented Editing message functionailty.

## Acceptance Criteria fulfillment

- [x] Implement the Editing Message functionality and the messages should be updated in realtime.

Fixes #74 

## Video/Screenshots

https://user-images.githubusercontent.com/89914602/210564367-b80b4456-0782-4792-87e8-ec75ed62e242.mp4

2023-01-04 13:24 UTC, ayush3160 commented
@sidmohanty11 , Can you please review this PR.

Thanks.

2023-01-05 15:25 UTC, sidmohanty11 requested changes
Hey @ayush3160 thanks a lot for the PR! The feature looks amazing!

2023-01-05 15:25 UTC, sidmohanty11 commented on src/index.js
> +  const [messageToEdit, setMessageToEdit] = useState({});
Let's not have any prop-drilling or global state that can affect rendering of components. As we are using zustand as our global state management can we please stick to it?

2023-01-05 19:52 UTC, ayush3160 commented
@sidmohanty11 , Please have a look I have used zustand for managing the state.

2023-01-06 07:39 UTC, sidmohanty11 requested changes

2023-01-06 07:39 UTC, sidmohanty11 commented on src/components/ChatInput/ChatInput.js
> +import { useToastStore, useUserStore, useEditMessageStore } from '../../store';
I think it will be better to use the useMessageStore rather than creating a new store

2023-01-06 18:16 UTC, ayush3160 commented
@sidmohanty11 , Please have a look I have used the message store

2023-01-07 16:39 UTC, merged